name: booking-order-app # change this to your app name
services:
  field-service: # change this to your service name
    container_name: field-service # change this to your service name
    platform: linux/amd64
    image: faisalabubakarriza/field-service:2 # change this to your image name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002" # change this to your port
    env_file:
      - .env
